version: 0.0
os: linux
files:
  - source: /	# install된 파일 중 destination으로 이동시킬 대상
    destination: /home/ec2-user/kkumtree/	# source에서 지정된 파일을 받을 위치
    overwrite: yes
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root