server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kkumtree?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
    generate-ddl: true
    show-sql: true