spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 20000
  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
