# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.13
  aws-code-deploy: circleci/aws-code-deploy@0.0.12

executors:
  my-executor:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/kkumtree

jobs:
  build:
    executor: my-executor

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Downloading Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew clean build

      - run:
          name: before_deploy
          command: |
            zip -r kkumtree-was scripts/*.sh appspec.yml build/libs/*.jar

      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    executor: my-executor

    steps:
      - attach_workspace:
          at: .

      - aws-s3/copy:
          from: kkumtree-was.zip
          to: 's3://kkumtree-build'
          aws-region: AWS_DEFAULT_REGION

      - aws-code-deploy/deploy-bundle:
          application-name: kkumtree
          deployment-group: kkumtree
          bundle-bucket:  kkumtree-build
          bundle-key: kkumtree-was
          bundle-type: zip

workflows:
  version: 2.1

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master